Documentat: Edited RU SDK docs.
2gis/native-sdk-android-demo pull request #20
Opened 2021-02-26 05:29 UTC by dkovalev-dio

https://github.com/2gis/digital-docs/issues/37

2021-02-26 05:49 UTC, ksidenko commented
@lagner а лицензия же нужна? Добавишь в репу?

2021-03-01 06:51 UTC, lagner requested changes

2021-03-01 06:51 UTC, lagner commented on docs/ru/examples.md
> +Для запуска примера склонируйте [GitHub-репозиторий 2GIS](https://github.com/2gis/native-sdk-android-demo) и задайте ваши ключи API в файле `local.properties` проекта:
Описание запуска примера полезно, но почему это "Начало работы"? Чтобы интегрировать SDK в свое приложение мне достаточно сделать [это](https://docs-canary.2gis.com/ru/android/native/maps/overview#nav-lvl1--Installation). Демо проект для этого вообще не нужен.

2021-03-01 06:51 UTC, lagner commented on docs/ru/examples.md
> +2. Инициализируйте виджет, вызвав метод [`getMapAsync`](/en/android/native/maps/reference/MapView#nav-lvl2--getMapAsync):
Технически мне кажется это не совсем корректно. Карта успешно инициализируется и без `getMapAsync`. Но без этого метода невозможно получить инстанс объекта Map, а значит не получится сделать с картой что-либо полезное

2021-03-01 06:51 UTC, lagner commented on docs/ru/examples.md
> +Текущая версия SDK по умолчанию использует предустановленные данные для отображения тайлов карты (map tiles). Также доступна экспериментальная функция, позволяющая загружать тайлы из онлайн-источника
Извините, тут у нас устаревший текст. Сейчас все ровно наоборот. По умолчанию мы работаем online и это уже не экспериментальный режим

2021-03-01 06:51 UTC, lagner commented on docs/ru/examples.md
> +Вы можете построить маршрут и отобразить его на карте с помощью Directions API:
Под капотом, по умолчанию, мы конечно ходим в Directions API. Но это не всегда. Иногда мы можем построить маршрут чисто offline. Стоит явно в документации указывать это?

2021-03-01 06:51 UTC, lagner commented on docs/ru/examples.md
> +   ```
Тут получился отступ с левого края, мне кажется он не нужен

2021-03-01 06:51 UTC, lagner commented on docs/ru/overview.md
> +Android Native SDK от 2GIS позволяет добавить [карту 2GIS](https://2gis.ru/) в ваше приложение под Android. С его помощью вы можете отображать карту на экране, добавлять на карту пользовательские мар
Может заменить *добавлять на карту пользовательские маркеры* на более общую формулировку *динамические объекты такие как маркеры, маршрут, геометрии и т.д.*

2021-03-01 06:51 UTC, lagner commented on docs/ru/overview.md
> +Кроме того, если вы планируете прокладывать маршруты на карте, то для вычисления и отображения оптимального маршрута вам понадобится отдельный ключ API - для [Directions API](/ru/api/navigation/direc
Не только для маршрутов. 1 ключ только для тайлов карты, 2й для всех походов в Web API т.е. это еще запросы в справочник

2021-03-03 05:13 UTC, dkovalev-dio commented on docs/ru/examples.md
> +2. Инициализируйте виджет, вызвав метод [`getMapAsync`](/en/android/native/maps/reference/MapView#nav-lvl2--getMapAsync):
Мы можем написать более нейтральный и корректный вариант «Получите объект карты Map, вызвав метод...»?

2021-03-03 05:15 UTC, dkovalev-dio commented on docs/ru/examples.md
> +Текущая версия SDK по умолчанию использует предустановленные данные для отображения тайлов карты (map tiles). Также доступна экспериментальная функция, позволяющая загружать тайлы из онлайн-источника
Тогда как должно быть написано?

По умолчанию мы подгружаем все из онлайна, но вы можете грузить тайлы и из оффлайна (предустановленные данные)? 

Может, тогда стоит дать читателю хотя бы наводку, как это сделать? Сейчас переключение источников для тайлов неочевидно что в том, что в другом случае.

2021-03-03 05:16 UTC, dkovalev-dio commented on docs/ru/examples.md
> +Вы можете построить маршрут и отобразить его на карте с помощью Directions API:
Это нужно обсуждать с @ksidenko.
Самостоятельно нужное решение мы не примем.

2021-03-03 05:18 UTC, dkovalev-dio commented on docs/ru/examples.md
> +Для запуска примера склонируйте [GitHub-репозиторий 2GIS](https://github.com/2gis/native-sdk-android-demo) и задайте ваши ключи API в файле `local.properties` проекта:
Вроде обсуждалось, что в примерах мы опираемся на репозиторий с примерами.
Уточню у @ksidenko.

2021-03-03 05:19 UTC, dkovalev-dio commented on docs/ru/examples.md
> +   ```
Тут список, поэтому отступ нужен. Можем обсудить саму необходимость списка здесь.
Мы полагаем, что со списком смотрится понятнее: видна четкая последовательность шагов.

2021-03-03 05:20 UTC, dkovalev-dio commented on docs/ru/overview.md
> +Android Native SDK от 2GIS позволяет добавить [карту 2GIS](https://2gis.ru/) в ваше приложение под Android. С его помощью вы можете отображать карту на экране, добавлять на карту пользовательские мар
Нужно обсудить вопрос с @ksidenko, это типовая формулировка, взятая из уже опубликованных доков.

2021-03-03 05:21 UTC, dkovalev-dio commented on docs/ru/overview.md
> +Кроме того, если вы планируете прокладывать маршруты на карте, то для вычисления и отображения оптимального маршрута вам понадобится отдельный ключ API - для [Directions API](/ru/api/navigation/direc
Обсудить с @ksidenko

2021-03-03 05:53 UTC, ksidenko commented on docs/ru/overview.md
> +Кроме того, если вы планируете прокладывать маршруты на карте, то для вычисления и отображения оптимального маршрута вам понадобится отдельный ключ API - для [Directions API](/ru/api/navigation/direc
речь про Places API

2021-05-06 06:07 UTC, lagner reviewed
начали работу с другой стороны. Текущий реквест закрывают т.к. тут будут более масштабные переделки

2021-05-06 06:07 UTC, closed without merging