Documentat: Updated README.md
2gis/native-sdk-android-demo pull request #22
Opened 2021-02-26 10:42 UTC by dkovalev-dio

https://github.com/2gis/digital-docs/issues/38

Про лицензию пока ничего не добавлял в README.

2021-03-01 06:56 UTC, lagner requested changes

2021-03-01 06:56 UTC, lagner commented on README.md
> +Additionally, if you plan to draw routes on the map, you will need a separate key—a [Directions API](https://docs.2gis.com/en/api/navigation/directions/overview) key—to calculate and display an optim
Я в другом ревью писал что на самом деле 2й ключ еще и влияет на все запросы в справочник. Мне кажется это нужно как-то обозначить.

2021-03-01 06:56 UTC, lagner commented on README.md
> +1. Declare a custom repository in your `build.gradle` file:
*custom repository* может замеить на *2GIS repository*? Не лучше будет?

2021-03-03 05:21 UTC, dkovalev-dio commented on README.md
> +1. Declare a custom repository in your `build.gradle` file:
Лучше будет. 
Заменим.

2021-05-06 06:06 UTC, lagner approved these changes
Залью в таком виде т.к. очень долго висит на ревью. Замечания поправим в следующей итерации

2021-05-06 06:06 UTC, merged