[SDK-#] New ci flow
2gis/native-sdk-android-demo pull request #9
Opened 2020-12-07 03:34 UTC by Sameri11

1. Мультибранч таска для проверки собираемости веток. Собирает артефакты, прогоняет тесты. Работает каждую ночь автоматически.
2. Релизная таска для получения релизного apk/bundle и остальных релизный действий с ними.

После влития нужно будет немного подправить таски и подготовить релизную (сделаю)

2020-12-09 12:10 UTC, lagner requested changes

2020-12-09 12:10 UTC, lagner commented on ci/all.jenkinsfile
> +                    catch (e) {
убери вообще этот блок, он же не делает ничего. Просто оставь *try* + *finally*

2020-12-09 12:10 UTC, lagner commented on ci/release.jenkinsfile
> +                    }
аналогично тому что выше. Лучше блок совсем убрать

2020-12-09 12:10 UTC, lagner commented on ci/release.jenkinsfile
> +                        sh "echo '\ndgisUnstrippedLibsUrl=${env.UNSTRIPPED_LIBS_URL}' >> local.properties"
там же выше формируется *local.properties*. Давай туда же запихнем. И красивше будет и однообразно как-то

2020-12-09 12:10 UTC, lagner commented on ci/release.jenkinsfile
> +                        script: "./gradlew clean build test lint bundle"
Сейчас не критично, но я здесь либо не понимаю, либо ошибку в логике вижу. unstripped библиотеки, если я не ошибаюсь, мы зальем на этом шаге. И после него уже тесты запустим, что странно. Т.к. если тесты не пройдут, нам и заливать ничего нет смысла

2020-12-09 14:56 UTC, Sameri11 commented on ci/release.jenkinsfile
> +                        script: "./gradlew clean build test lint bundle"
Не совсем. Именно грузим unstripped мы в стейдже `Release Deploy` c помощью `./gradlew app:uploadCrashlyticsSymbolFileRelease`

2020-12-09 15:00 UTC, Sameri11 commented on ci/all.jenkinsfile
> +                    catch (e) {
Ты предлагаешь `throw e` в блок `finaly` переместить, правильно?

2020-12-09 15:03 UTC, Sameri11 commented on ci/all.jenkinsfile
> +                                sleep 5
Это прям костыли, потому что ничего более простого не получилось запустить :( Эмуль запускается в фоне, и чтобы флоу CI прошел дальше, и нам нужно его опрашивать, чтобы понять, что он ок запустился. Запускается он за 10-15-20 секунд до состояния `Booted`, поэтому так.
Надо бы, наверное, это все делегировать грэдлу, но кажется что "с ноги" не получиться такое сделать, поэтому пока так.

2020-12-09 15:22 UTC, lagner commented on ci/all.jenkinsfile
> +                    catch (e) {
неа. 
```groovy
try {
    // do smth
} finally {
    // cleaning
}
```
В таком коде исключение вылетит из этого блока, но *finally* отработает в любом случае.
По сути ровно то же что у тебя написано

2020-12-09 15:23 UTC, Sameri11 commented on ci/all.jenkinsfile
> +                    catch (e) {
Так нам же надо, чтобы это исключение выбросилось, а не исчезло.

2020-12-09 15:34 UTC, Sameri11 commented on ci/all.jenkinsfile
> +                    catch (e) {
Все, я понял. Я почему-то думал (и даже где-то напарывался), что try без catch просто проглотит исключение. Или путаю с чем-то другим.
Поправлю

2020-12-09 15:36 UTC, Sameri11 commented on ci/all.jenkinsfile
> +                                    /opt/android-sdk/platform-tools/adb logcat -d > logcat.txt
++

2020-12-09 15:36 UTC, Sameri11 commented on ci/release.jenkinsfile
> +                    }
++

2020-12-09 15:36 UTC, Sameri11 commented on ci/release.jenkinsfile
> +                        sh "echo '\ndgisUnstrippedLibsUrl=${env.UNSTRIPPED_LIBS_URL}' >> local.properties"
++

2020-12-10 05:24 UTC, lagner approved these changes

2020-12-10 05:24 UTC, lagner commented on ci/release.jenkinsfile
> +                            dgisUnstrippedLibsDir=$(pwd)/build/app/nativeLibs
А когда в круглых скобках он тоже подставляет?

2020-12-10 05:53 UTC, merged